name: Daily Event Update

on:
  schedule:
    - cron: '0 23 * * *'  # 每天UTC时间的23:00，相当于NZDT的12:00PM
  workflow_dispatch:  # 手动触发工作流

jobs:
  send_event_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Set up Chrome
        # setup-chrome Action
        uses: browser-actions/setup-chrome@v1

      steps:
        - uses: actions/checkout@v2
        - uses: nanasess/setup-chromedriver@v2
          with:
            # Optional: do not specify to match Chrome's version
            chromedriver-version: '88.0.4324.96'
        - run: |
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run event script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python event_script.py
