name: Daily Event Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'  # NZDT 12:00PM
  workflow_dispatch:  # Manual trigger

jobs:
  send_event_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 webdriver-manager  # Ensure webdriver-manager is included

      - name: Verify Installed Packages
        run: |
          pip list  # Check if webdriver-manager is listed here for debugging

      - name: Run event script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python event_script.py
