name: Daily Event Update

on:
  schedule:
    - cron: '0 23 * * *'  # NZDT的12:00PM
  workflow_dispatch:  # 手动触发工作流

jobs:
  send_event_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '130'          # 使用指定的Chrome版本
          install-chromedriver: false     # 禁用自动安装不兼容的ChromeDriver

      - name: Install compatible ChromeDriver
        run: |
          # Download ChromeDriver version compatible with Chrome 130
          curl -sS -o /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run event script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python event_script.py
